####################################################################################
## Arty A7-100 Constraints for MII Ethernet Receiver
## Board: Arty A7-100T (XC7A100T-1CSG324C)
## PHY: TI DP83848J (MII Interface, 10/100 Mbps)
####################################################################################

####################################################################################
## System Clock (100 MHz)
####################################################################################
set_property -dict { PACKAGE_PIN E3  IOSTANDARD LVCMOS33 } [get_ports { CLK }];

####################################################################################
## Reset Button (BTN0 - active HIGH when pressed)
####################################################################################
set_property -dict { PACKAGE_PIN D9  IOSTANDARD LVCMOS33 } [get_ports { reset_btn }];

####################################################################################
## MII Ethernet PHY (TI DP83848J)
####################################################################################

## Reference Clock (FPGA generates 25 MHz for PHY)
set_property -dict { PACKAGE_PIN G18  IOSTANDARD LVCMOS33 } [get_ports { eth_ref_clk }];

## PHY Reset (active LOW)
set_property -dict { PACKAGE_PIN C16  IOSTANDARD LVCMOS33 } [get_ports { eth_rstn }];

## MII RX Interface (PHY -> FPGA)
set_property -dict { PACKAGE_PIN F15  IOSTANDARD LVCMOS33 } [get_ports { eth_rx_clk }];
set_property -dict { PACKAGE_PIN G16  IOSTANDARD LVCMOS33 } [get_ports { eth_rx_dv }];
set_property -dict { PACKAGE_PIN D18  IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[0] }];
set_property -dict { PACKAGE_PIN E17  IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[1] }];
set_property -dict { PACKAGE_PIN E18  IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[2] }];
set_property -dict { PACKAGE_PIN G17  IOSTANDARD LVCMOS33 } [get_ports { eth_rxd[3] }];
set_property -dict { PACKAGE_PIN C17  IOSTANDARD LVCMOS33 } [get_ports { eth_rx_er }];

## MII TX Interface (FPGA -> PHY) - Not used but must be constrained
set_property -dict { PACKAGE_PIN H16  IOSTANDARD LVCMOS33 } [get_ports { eth_tx_clk }];
set_property -dict { PACKAGE_PIN H15  IOSTANDARD LVCMOS33 } [get_ports { eth_tx_en }];
set_property -dict { PACKAGE_PIN H14  IOSTANDARD LVCMOS33 } [get_ports { eth_txd[0] }];
set_property -dict { PACKAGE_PIN J14  IOSTANDARD LVCMOS33 } [get_ports { eth_txd[1] }];
set_property -dict { PACKAGE_PIN J13  IOSTANDARD LVCMOS33 } [get_ports { eth_txd[2] }];
set_property -dict { PACKAGE_PIN H17  IOSTANDARD LVCMOS33 } [get_ports { eth_txd[3] }];

## MII Management Interface (Optional - not implemented yet)
set_property -dict { PACKAGE_PIN F16  IOSTANDARD LVCMOS33 } [get_ports { eth_mdc }];
set_property -dict { PACKAGE_PIN K13  IOSTANDARD LVCMOS33 } [get_ports { eth_mdio }];

## MII Status (half-duplex only)
set_property -dict { PACKAGE_PIN D17  IOSTANDARD LVCMOS33 } [get_ports { eth_col }];
set_property -dict { PACKAGE_PIN G14  IOSTANDARD LVCMOS33 } [get_ports { eth_crs }];

####################################################################################
## LEDs
####################################################################################

## Individual LEDs (frame counter)
set_property -dict { PACKAGE_PIN H5   IOSTANDARD LVCMOS33 } [get_ports { led[0] }];
set_property -dict { PACKAGE_PIN J5   IOSTANDARD LVCMOS33 } [get_ports { led[1] }];
set_property -dict { PACKAGE_PIN T9   IOSTANDARD LVCMOS33 } [get_ports { led[2] }];
set_property -dict { PACKAGE_PIN T10  IOSTANDARD LVCMOS33 } [get_ports { led[3] }];

## RGB LEDs (status indicators)
set_property -dict { PACKAGE_PIN F6   IOSTANDARD LVCMOS33 } [get_ports { led0_g }];  # Activity (green)
set_property -dict { PACKAGE_PIN G4   IOSTANDARD LVCMOS33 } [get_ports { led1_b }];  # PHY ready (blue)
set_property -dict { PACKAGE_PIN J3   IOSTANDARD LVCMOS33 } [get_ports { led2_r }];  # Error (red)

####################################################################################
## Timing Constraints
####################################################################################

## System clock (100 MHz)
create_clock -period 10.000 -name sys_clk [get_ports CLK]

## Reference clock (generated by FPGA for PHY)
create_generated_clock -name eth_ref_clk \
    -source [get_pins ref_clock_gen/CLKOUT0] \
    -divide_by 1 \
    [get_ports eth_ref_clk]

## RX clock from PHY (25 MHz for 100 Mbps mode)
create_clock -period 40.000 -name eth_rx_clk [get_ports eth_rx_clk]

## TX clock from PHY (25 MHz for 100 Mbps mode)
create_clock -period 40.000 -name eth_tx_clk [get_ports eth_tx_clk]

## Input delays for MII RX data (relative to eth_rx_clk)
## MII spec: setup/hold window is approximately 10ns
set_input_delay -clock eth_rx_clk -max 10.0 [get_ports {eth_rxd[*] eth_rx_dv eth_rx_er}]
set_input_delay -clock eth_rx_clk -min 0.0 [get_ports {eth_rxd[*] eth_rx_dv eth_rx_er}]

## Output delays for MII TX data (relative to eth_tx_clk)
## Not critical since we're not transmitting, but good practice
set_output_delay -clock eth_tx_clk -max 10.0 [get_ports {eth_txd[*] eth_tx_en}]
set_output_delay -clock eth_tx_clk -min 0.0 [get_ports {eth_txd[*] eth_tx_en}]

## Clock domain crossing constraints
## eth_rx_clk (25 MHz) -> sys_clk (100 MHz) via 2FF synchronizer
set_max_delay -from [get_clocks eth_rx_clk] -to [get_clocks sys_clk] 40.0
set_max_delay -from [get_clocks sys_clk] -to [get_clocks eth_rx_clk] 10.0

## Mark asynchronous clock domains
set_clock_groups -asynchronous \
    -group [get_clocks sys_clk] \
    -group [get_clocks eth_rx_clk] \
    -group [get_clocks eth_tx_clk] \
    -group [get_clocks eth_ref_clk]

####################################################################################
## Configuration
####################################################################################

## Configuration bank voltage
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

## Bitstream options
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
