#pragma once

#include <string>
#include <cstdint>

namespace mm {

// BBO data structure (imported from gateway)
struct BBO {
    std::string symbol;
    double bid_price = 0.0;
    uint32_t bid_shares = 0;
    double ask_price = 0.0;
    uint32_t ask_shares = 0;
    double spread = 0.0;
    uint64_t timestamp_ns = 0;
    bool valid = false;
};

// Quote generated by market maker
struct Quote {
    std::string symbol;
    double bid_price = 0.0;
    int bid_size = 0;
    double ask_price = 0.0;
    int ask_size = 0;
    double fair_value = 0.0;
    uint64_t timestamp_ns = 0;
    bool valid = false;
};

// Order side
enum class Side {
    BUY,
    SELL
};

// Order type
enum class OrderType {
    LIMIT,
    MARKET
};

// Order status
enum class OrderStatus {
    PENDING,
    FILLED,
    PARTIAL_FILL,
    CANCELLED,
    REJECTED
};

// Order structure
struct Order {
    std::string symbol;
    Side side;
    OrderType type;
    double price = 0.0;
    int quantity = 0;
    int filled_quantity = 0;
    OrderStatus status = OrderStatus::PENDING;
    uint64_t order_id = 0;
    uint64_t timestamp_ns = 0;
};

// Trade fill
struct Fill {
    std::string symbol;
    Side side;
    double price = 0.0;
    int shares = 0;
    uint64_t timestamp_ns = 0;
};

// Helper functions
inline const char* sideToString(Side side) {
    return (side == Side::BUY) ? "BUY" : "SELL";
}

inline const char* orderStatusToString(OrderStatus status) {
    switch (status) {
        case OrderStatus::PENDING: return "PENDING";
        case OrderStatus::FILLED: return "FILLED";
        case OrderStatus::PARTIAL_FILL: return "PARTIAL_FILL";
        case OrderStatus::CANCELLED: return "CANCELLED";
        case OrderStatus::REJECTED: return "REJECTED";
        default: return "UNKNOWN";
    }
}

} // namespace mm
